seo: 
  site_name: OnememoryDesign. | Web Design & Development
  title: OnememoryDesign.
  description: Professional web design & development – custom, responsive, and SEO-optimized websites for businesses, freelancers, and creatives.
  keywords: [
    'web design', 'web development', 'responsive web design', 'seo-optimized websites', 
    'custom website design', 'professional website', 'modern web design', 'custom web development', 
    'wordpress web design', 'business web design', 'freelancer web design', 'startup web design', 
    'landing page design', 'ux/ui design', 'seo-friendly websites', 'e-commerce web design', 
    'web design for restaurants', 'creative web design', 'minimalist web design', 'HTML and CSS'
  ]
  social_image: /images/logo.png
  author: Jenny & Patrick
  favicon_image: /images/logo.png
social:
  instagram_username: https://www.instagram.com/onememory.design
  facebook_url: https://www.facebook.com/profile.php?id=61572833130208
  pinterest: https://www.pinterest.com/onememorydesign/